# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param simulator.modelsimInstallPath C:/intelFPGA_lite/16.1/modelsim_ase/win32aloem
create_project -in_memory -part xc7a35ticsg324-1L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/FPGA/Xilinx/arty_ntp_client/vivado/arty_ntp_client.cache/wt [current_project]
set_property parent.project_path D:/FPGA/Xilinx/arty_ntp_client/vivado/arty_ntp_client.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo d:/FPGA/Xilinx/arty_ntp_client/vivado/arty_ntp_client.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/FPGA/Xilinx/arty_ntp_client/hdl/uart/UART_TX.vhd
  D:/FPGA/Xilinx/arty_ntp_client/hdl/add_crc32.vhd
  D:/FPGA/Xilinx/arty_ntp_client/hdl/add_preamble.vhd
  D:/FPGA/Xilinx/arty_ntp_client/hdl/ntp_pkg.vhd
  D:/FPGA/Xilinx/arty_ntp_client/hdl/arp_decoder.vhd
  D:/FPGA/Xilinx/arty_ntp_client/hdl/axis_arbiter.vhd
  D:/FPGA/Xilinx/arty_ntp_client/hdl/axis_eth.vhd
  D:/FPGA/Xilinx/arty_ntp_client/hdl/axis_ntp.vhd
  D:/FPGA/Xilinx/arty_ntp_client/hdl/dxdisplay/display_top.vhd
  D:/FPGA/Xilinx/arty_ntp_client/hdl/dxdisplay/dx_display.vhd
  D:/FPGA/Xilinx/arty_ntp_client/hdl/dxdisplay/dx_display_xmit.vhd
  D:/FPGA/Xilinx/arty_ntp_client/hdl/ipv4_decoder.vhd
  D:/FPGA/Xilinx/arty_ntp_client/hdl/main_clock.vhd
  D:/FPGA/Xilinx/arty_ntp_client/hdl/ntp_client.vhd
  D:/FPGA/Xilinx/arty_ntp_client/hdl/packet_decoder.vhd
  D:/FPGA/Xilinx/arty_ntp_client/hdl/resetgen.vhd
  D:/FPGA/Xilinx/arty_ntp_client/hdl/uart/uart_mux.vhd
  D:/FPGA/Xilinx/arty_ntp_client/hdl/uart/uartdump.vhd
  D:/FPGA/Xilinx/arty_ntp_client/hdl/arty_ntp_client.vhd
}
read_ip -quiet D:/FPGA/Xilinx/arty_ntp_client/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all d:/FPGA/Xilinx/arty_ntp_client/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Xilinx/arty_ntp_client/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Xilinx/arty_ntp_client/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

read_ip -quiet D:/FPGA/Xilinx/arty_ntp_client/ip/fifo_2048x9/fifo_2048x9.xci
set_property used_in_implementation false [get_files -all d:/FPGA/Xilinx/arty_ntp_client/ip/fifo_2048x9/fifo_2048x9.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Xilinx/arty_ntp_client/ip/fifo_2048x9/fifo_2048x9_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Xilinx/arty_ntp_client/ip/fifo_2048x9/fifo_2048x9_ooc.xdc]

read_ip -quiet D:/FPGA/Xilinx/arty_ntp_client/ip/axis_switch_0/axis_switch_0.xci
set_property used_in_implementation false [get_files -all d:/FPGA/Xilinx/arty_ntp_client/ip/axis_switch_0/axis_switch_0_ooc.xdc]

read_ip -quiet D:/FPGA/Xilinx/arty_ntp_client/ip/fifo_2048x8/fifo_2048x8.xci
set_property used_in_implementation false [get_files -all d:/FPGA/Xilinx/arty_ntp_client/ip/fifo_2048x8/fifo_2048x8.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Xilinx/arty_ntp_client/ip/fifo_2048x8/fifo_2048x8_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Xilinx/arty_ntp_client/ip/fifo_2048x8/fifo_2048x8_ooc.xdc]

read_ip -quiet D:/FPGA/Xilinx/arty_ntp_client/ip/fifo_2048x9_dv/fifo_2048x9_dv.xci
set_property used_in_implementation false [get_files -all d:/FPGA/Xilinx/arty_ntp_client/ip/fifo_2048x9_dv/fifo_2048x9_dv.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Xilinx/arty_ntp_client/ip/fifo_2048x9_dv/fifo_2048x9_dv_clocks.xdc]
set_property used_in_implementation false [get_files -all d:/FPGA/Xilinx/arty_ntp_client/ip/fifo_2048x9_dv/fifo_2048x9_dv_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/FPGA/Xilinx/arty_ntp_client/constraints/arty.xdc
set_property used_in_implementation false [get_files D:/FPGA/Xilinx/arty_ntp_client/constraints/arty.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top arty_ntp_client -part xc7a35ticsg324-1L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef arty_ntp_client.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file arty_ntp_client_utilization_synth.rpt -pb arty_ntp_client_utilization_synth.pb"
