# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/FPGA/Xilinx/arty_ntp_client/constraints/arty.xdc

# IP: D:/FPGA/Xilinx/arty_ntp_client/ip/clk_wiz_0/clk_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# IP: D:/FPGA/Xilinx/arty_ntp_client/ip/fifo_2048x9/fifo_2048x9.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_2048x9 || ORIG_REF_NAME==fifo_2048x9} -quiet] -quiet

# IP: D:/FPGA/Xilinx/arty_ntp_client/ip/axis_switch_0/axis_switch_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_switch_0 || ORIG_REF_NAME==axis_switch_0} -quiet] -quiet

# IP: D:/FPGA/Xilinx/arty_ntp_client/ip/fifo_2048x8/fifo_2048x8.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_2048x8 || ORIG_REF_NAME==fifo_2048x8} -quiet] -quiet

# IP: D:/FPGA/Xilinx/arty_ntp_client/ip/fifo_2048x9_dv/fifo_2048x9_dv.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_2048x9_dv || ORIG_REF_NAME==fifo_2048x9_dv} -quiet] -quiet
